//! US keyboard layout (printable subset) -- char -> (code, keyCode).
//! Ported 1:1 from Playwright's usKeyboardLayout.js so synthetic key
//! events carry the same code/keyCode pairs Firefox's TextInputProcessor
//! maps to real keys. Letters worked with "Key{A}"; digits/punctuation
//! failed with the old fabricated codes ("Key0"/"Key." are not valid DOM
//! `code` values -- TIP treats them as non-printable and inserts nothing).
pub const US_LAYOUT: &[(char, &str, u32)] = &[
    (' ', "Space", 32),
    ('!', "Digit1", 49),
    ('#', "Digit3", 51),
    ('$', "Digit4", 52),
    ('%', "Digit5", 53),
    ('&', "Digit7", 55),
    ('\'', "Quote", 222),
    ('(', "Digit9", 57),
    (')', "Digit0", 48),
    ('*', "Digit8", 56),
    ('+', "Equal", 187),
    (',', "Comma", 188),
    ('-', "Minus", 189),
    ('.', "Period", 190),
    ('/', "Slash", 191),
    ('0', "Digit0", 48),
    ('1', "Digit1", 49),
    ('2', "Digit2", 50),
    ('3', "Digit3", 51),
    ('4', "Digit4", 52),
    ('5', "Digit5", 53),
    ('6', "Digit6", 54),
    ('7', "Digit7", 55),
    ('8', "Digit8", 56),
    ('9', "Digit9", 57),
    (':', "Semicolon", 186),
    (';', "Semicolon", 186),
    ('<', "Comma", 188),
    ('=', "Equal", 187),
    ('>', "Period", 190),
    ('?', "Slash", 191),
    ('@', "Digit2", 50),
    ('A', "KeyA", 65),
    ('B', "KeyB", 66),
    ('C', "KeyC", 67),
    ('D', "KeyD", 68),
    ('E', "KeyE", 69),
    ('F', "KeyF", 70),
    ('G', "KeyG", 71),
    ('H', "KeyH", 72),
    ('I', "KeyI", 73),
    ('J', "KeyJ", 74),
    ('K', "KeyK", 75),
    ('L', "KeyL", 76),
    ('M', "KeyM", 77),
    ('N', "KeyN", 78),
    ('O', "KeyO", 79),
    ('P', "KeyP", 80),
    ('Q', "KeyQ", 81),
    ('R', "KeyR", 82),
    ('S', "KeyS", 83),
    ('T', "KeyT", 84),
    ('U', "KeyU", 85),
    ('V', "KeyV", 86),
    ('W', "KeyW", 87),
    ('X', "KeyX", 88),
    ('Y', "KeyY", 89),
    ('Z', "KeyZ", 90),
    ('[', "BracketLeft", 219),
    ('^', "Digit6", 54),
    ('_', "Minus", 189),
    ('`', "Backquote", 192),
    ('a', "KeyA", 65),
    ('b', "KeyB", 66),
    ('c', "KeyC", 67),
    ('d', "KeyD", 68),
    ('e', "KeyE", 69),
    ('f', "KeyF", 70),
    ('g', "KeyG", 71),
    ('h', "KeyH", 72),
    ('i', "KeyI", 73),
    ('j', "KeyJ", 74),
    ('k', "KeyK", 75),
    ('l', "KeyL", 76),
    ('m', "KeyM", 77),
    ('n', "KeyN", 78),
    ('o', "KeyO", 79),
    ('p', "KeyP", 80),
    ('q', "KeyQ", 81),
    ('r', "KeyR", 82),
    ('s', "KeyS", 83),
    ('t', "KeyT", 84),
    ('u', "KeyU", 85),
    ('v', "KeyV", 86),
    ('w', "KeyW", 87),
    ('x', "KeyX", 88),
    ('y', "KeyY", 89),
    ('z', "KeyZ", 90),
    ('{', "BracketLeft", 219),
    ('|', "Backslash", 220),
    ('~', "Backquote", 192),
];

/// (code, keyCode) for a printable ASCII char, US layout.
pub fn describe(ch: char) -> Option<(&'static str, u32)> {
    US_LAYOUT
        .iter()
        .find(|(c, _, _)| *c == ch)
        .map(|(_, code, kc)| (*code, *kc))
}
